Update Build-OP-MangoPi_M28K.yml

diff --git a/.github/workflows/Build-OP-MangoPi_M28K.yml b/.github/workflows/Build-OP-MangoPi_M28K.yml
--- a/.github/workflows/Build-OP-MangoPi_M28K.yml
+++ b/.github/workflows/Build-OP-MangoPi_M28K.yml
@@ -48,15 +48,17 @@ jobs:
         echo "status=success" >> ${GITHUB_OUTPUT}
         
     - name: Clone source code
-      id: codes
       if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
       run: |
         git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
+        git clone --depth 1 https://github.com/vernesong/OpenClash.git OpenClash
         cd openwrt
         echo 'src-git Qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default
         echo 'src-git istore https://github.com/linkease/istore;main' >> feeds.conf.default
         echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >> feeds.conf.default
         echo 'src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' >> feeds.conf.default
+        echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"
+        echo "src-git fancontrol https://github.com/rockjake/luci-app-fancontrol.git" >> "feeds.conf.default"
 
     - name: Free up disk space
       run: |
@@ -70,9 +72,9 @@ jobs:
       working-directory: ./openwrt
       run: |
         ./scripts/feeds update -a
-        sed -i 's/PKG_VERSION:=0.46.033/PKG_VERSION:=0.46.086/' feeds/luci/applications/luci-app-openclash/Makefile
-        ./scripts/feeds install -a
-        ./scripts/feeds install -a -f -p modem
+        rm -rf feeds/luci/applications/luci-app-openclash
+        cp -r ../OpenClash/luci-app-openclash feeds/luci/applications/
+        ./scripts/feeds install -a -f
 
     - name: Configuration Customization
       run: |
@@ -89,16 +91,13 @@ jobs:
         cd openwrt && make defconfig
         
     - name: Download package
-      id: package
+      working-directory: ./openwrt
       run: |
-        cd openwrt/
-        make download -j$(nproc) || { echo "❌ 下载失败"; exit 1; }
+        make download -j$(nproc) || { echo "Download failed"; exit 1; }
         find dl -size -1024c -delete
-        echo "status=success" >> ${GITHUB_OUTPUT}
  
     - name: Compile the OpenWrt
-      id : compile
-      if : steps.package.outputs.status == 'success'
+      id: compile
       run: |
         cd openwrt/
         if [[ "${{ inputs.log_switch }}" == "true" ]]; then
@@ -109,8 +108,8 @@ jobs:
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-        echo "status=success" >> ${GITHUB_OUTPUT}
-
+        echo "status=success" >> $GITHUB_OUTPUT
+        
     - name: Organize files
       id: organize
       if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
@@ -137,7 +136,7 @@ jobs:
         --------------------------
         设备: MangoPi M28K
         时间: $(date +"%Y-%m-%d %H:%M")
-        内核: $(grep 'CONFIG_LINUX_6_12=y' .config | cut -c 14-17)
+        内核: ${{ inputs.device_config }}
         插件：qmodem，istore,dockerman等等
         EOF
 
